# Generated by Django 4.2.9 on 2024-01-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='newfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='newfile',
            name='upload',
            field=models.FileField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
